name: Create Issue in Blog Repo
on:
  workflow_dispatch

env:
  VERSION: 3.26.0
  
jobs:
  create-issue:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Issue
        run: |
          TITLE="Create a blog post for release v$VERSION"
          echo "Issue title: $TITLE"
          sed ':a;N;$!ba;s/\n/\\n/g' ./.github/workflows/md/blog-issue-template.md > output_file.txt
          BODY="$(cat output_file.txt)"

          echo "Body: $BODY"

          curl -X POST \
              -H "Authorization: token ${{ secrets.CYTOSCAPE_JS_BLOG_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/AkMo3/cytoscape.js-blog/issues" \
              -d "{\"title\":\"$TITLE\",\"body\":\"$BODY\"}"
