name: Feature Release Test

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version of new Release

jobs:  
  feature-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout patch branch
        uses: actions/checkout@v3
        with:
          ref: 'unstable'
          fetch-depth: 0
      - name: Get new version string
        id: get_new_patch_version
        run: |
          if [[ "${{ github.event.inputs.version }}" != "" ]]; then
            echo "VERSION=${{ github.event.inputs.version }}"  >> $GITHUB_ENV
          else 
            chmod +rx ./.github/workflows/scripts/new-feature-version.sh
            . ./.github/workflows/scripts/new-feature-version.sh
          fi
        shell: bash
      - name: See new feature version
        run: echo branch ${{ env.VERSION }}
        shell: bash
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - name: Merge unstable to master branch
        run: |
          chmod +rx ./.github/workflows/scripts/merge_unstable_to_master.sh
          . ./.github/workflows/scripts/merge_unstable_to_master.sh
        
        
