name: Feature Release Test

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version of new Release

jobs:  
  feature-release-test:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: checkout patch branch
        uses: actions/checkout@v3
        with:
          ref: 'unstable'
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Get new version string
        id: get_new_patch_version
        run: |
          pwd
          if [[ "${{ github.event.inputs.version }}" != "" ]]; then
            echo "VERSION=${{ github.event.inputs.version }}"  >> $GITHUB_ENV
          else 
            chmod +rx ./.github/workflows/scripts/new-feature-version.sh
            . ./.github/workflows/scripts/new-feature-version.sh
          fi
        shell: bash
      - name: See new feature and jq version
        run: |
          echo VERSION ${{ env.VERSION }}
          jq --version
        shell: bash
      - name: Checkout Master Branch
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - name: Merge unstable to master branch
        run: |
          curl -L -o merge_unstable_to_master.sh https://raw.githubusercontent.com/AkMo3/cytoscape.js/unstable/.github/workflows/scripts/merge_unstable_to_master.sh
          chmod +rx ./merge_unstable_to_master.sh
          . merge_unstable_to_master.sh
      - name: Install dependencies
        run: npm install
      # - name: Run tests
      #   run : |
      #     npm test
      - name: Pre Release Tests
        run: |
          chmod +rx ./.github/workflows/scripts/pre_release_test.sh
          . ./.github/workflows/scripts/pre_release_test.sh    
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CYTOSCAPE_PUBLISH_TOKEN }}
        
