name: Patch Release Test

on:
  milestone:
    types: [closed]

jobs:  
  patch-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Patch Branch
        id: get_patch_branch_from_milestone
        run: |
          milestone=${{ github.event.milestone.title }}
          curl -L -o Parse-Branch.sh https://raw.githubusercontent.com/AkMo3/cytoscape.js/unstable/.github/workflows/parse-branch-from-milestone.sh
          chmod +rx ./Parse-Branch.sh
          . Parse-Branch.sh $milestone
        shell: bash
      - name: See patch branch
        run: echo branch ${{ env.PATCH_BRANCH }}
        shell: bash
      - name: checkout patch branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.PATCH_BRANCH }}
      - name: Get new version string
        id: get_new_patch_version
        run: |
          curl -L -o new-patch-version.sh https://raw.githubusercontent.com/AkMo3/cytoscape.js/unstable/.github/workflows/scripts/new-patch-version.sh
          chmod +rx ./new-patch-version.sh
          . new-patch-version.sh
        shell: bash
      - name: See new patch version
        run: echo "# version:" ${{ env.NEW_PATCH_VERSION }}
        shell: bash
      - name: Run tests
        run : |
          npm run test
        
        
