name: Patch Release Test

on:
  milestone:
    types: [closed]

jobs:  
  feature-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Patch Branch
        id: get_patch_branch_from_milestone
        run: |
          milestone=${{ github.event.milestone.title }}
          curl -L -o Parse-Branch.sh https://raw.githubusercontent.com/AkMo3/cytoscape.js/unstable/.github/workflows/parse-branch-from-milestone.sh
          chmod +rx ./Parse-Branch.sh
          . Parse-Branch.sh $milestone
        shell: bash
      - run: echo branch ${{ env.PATCH_BRANCH }}
        shell: bash
        
