name: Release

on:
  milestone:
    types: [closed]
    
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      releaseType:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Select type of release'
        # Default release type is patch
        default: 'patch'
        # Input has to be provided for the workflow to run
        required: true
        # Type of options to be provided
        type: choice
        # List of options
        options:
        - patch
        - feature

jobs:
  log-the-inputs:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Release Type: $TYPE"
        env:
          TYPE: ${{ inputs.releaseType }}
  
  run-on-milestone:
    if: ${{ github.event_name == 'milestone' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Release Type: $TYPE"
        env:
          TYPE: 'feature'
    
