name: Release

on:
  milestone:
    types: [closed]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      releaseType:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Select type of release'
        # Default release type is patch
        default: 'patch'
        # Input has to be provided for the workflow to run
        required: true
        # Type of options to be provided
        type: choice
        # List of options
        options:
        - patch
        - feature

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
